### ISSUE TITLE
Master fails with Dart VM version: 2.0.0-dev.39.0

### ISSUE THREAD

**Issue by grouma** [dart-lang/test#788] opened 2018-03-19 21:34 UTC
Failures appear to be Dart2JS related. Likely need to use the old frontend. See https://travis-ci.org/dart-lang/test/builds/354771199

**Comment by natebosch** [comment] 2018-03-19 21:37
Using the old frontend is a good temporary fix to get unblocked. Longer term we'll want to make sure we're using arguments compatible with the latest Dart2Js approach.

**Comment by nex3** [comment] 2018-03-19 22:57
I believe this is caused by dart-lang/sdk#32561, which means it should be fixed with the next dev SDK roll.

**Comment by natebosch** [comment] 2018-03-19 23:06
Can we rely on [`PackageResolver.current.processArgument`](https://github.com/dart-lang/test/blob/df2ede529a99aa1fe8765da9657fd2ccd977cd2b/lib/src/runner/compiler_pool.dart#L70) _always_ choosing `--package` instead of `--package-root`?

I wasn't sure if all the failures where with `--pub-serve` or not

**Comment by nex3** [comment] 2018-03-19 23:13
> Can we rely on [`PackageResolver.current.processArgument`](https://github.com/dart-lang/test/blob/df2ede529a99aa1fe8765da9657fd2ccd977cd2b/lib/src/runner/compiler_pool.dart#L70) _always_ choosing `--package` instead of `--package-root`?

As long as it never depends on transformed code, it should be fine. If it *is* being run using a package root, there's not going to be any valid way of invoking dart2js.

> I wasn't sure if all the failures where with `--pub-serve` or not

I didn't do a thorough check but it looked like they were at a glance.

**Comment by natebosch** [comment] 2018-03-22 18:15
Initial workaround: #793

Still need to figure out a better long term solution

**Comment by nex3** [comment] 2018-03-22 18:20
Once https://github.com/dart-lang/sdk/issues/32633 is fixed (which it should be soon; it's marked P1 and there's a lot of activity around it) we'll be fine here.

**Closed** 2019-02-23 02:47 UTC
Labels: blocked
