### ISSUE TITLE
Allow users to pass in custom flags to testing platforms

### ISSUE THREAD

**Issue by jayudey-wf** [dart-lang/test#551] opened 2017-02-22 21:35 UTC
It would be nice to be able to pass in flags to the testing platforms that you are executing on rather then them being hardcoded to allow for a more configurable testing environment. 

( https://github.com/dart-lang/test/blob/8dbf5ff95292a6067cee91322c674b45334e44b0/lib/src/runner/browser/dartium.dart#L41 )

**Comment by nex3** [comment] 2017-02-22 22:55
Duplicate of #391.

**Closed by nex3** 2017-02-22 22:55 UTC
