### ISSUE TITLE
Sentinel Expired error when running coverage on Windows package

### ISSUE THREAD

**Issue by timsneath** [dart-lang/test#1698] opened 2022-05-08 15:03 UTC
Received this error this morning while running coverage on a project. 

```
[C:\src\winmd] coverage
00:09 +48: test\scope_test.dart: Scope name is as expected                                                                                              [Sentinel kind: Expired, valueAsString: <expired>] from getIsolateGroup()
package:vm_service/src/vm_service.dart 1734:45        new _OutstandingRequest
package:vm_service/src/vm_service.dart 2245:21        VmService._call
package:vm_service/src/vm_service.dart 1978:7         VmService.getIsolateGroup
package:coverage/src/collect.dart 131:40              _getAllCoverage
package:coverage/src/collect.dart 84:12               collect
package:test_core/src/runner/vm/platform.dart 196:10  _gatherCoverage
package:test_core/src/runner/runner_suite.dart 79:8   RunnerSuite.gatherCoverage
package:test_core/src/runner/coverage.dart 16:18      writeCoverage
package:test_core/src/runner/engine.dart 270:36       Engine.run.<fn>.<fn>

This is an unexpected error. Please file an issue at http://github.com/dart-lang/test
with the stack trace and instructions for reproducing the error.
Unhandled exception:
[Sentinel kind: Expired, valueAsString: <expired>] from getIsolateGroup()
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1734:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2245:21)
#2      VmService.getIsolateGroup (package:vm_service/src/vm_service.dart:1978:7)
#3      _getAllCoverage (package:coverage/src/collect.dart:131:40)
<asynchronous suspension>
#4      collect (package:coverage/src/collect.dart:84:12)
<asynchronous suspension>
#5      _gatherCoverage (package:test_core/src/runner/vm/platform.dart:196:10)
<asynchronous suspension>
#6      RunnerSuite.gatherCoverage (package:test_core/src/runner/runner_suite.dart:79:8)
<asynchronous suspension>
#7      writeCoverage (package:test_core/src/runner/coverage.dart:16:18)
<asynchronous suspension>
#8      Engine.run.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/engine.dart:270:36)
<asynchronous suspension>
```

## dart version

Dart SDK version: 2.18.0-85.0.dev (dev) (Wed May 4 12:05:31 2022 -0700) on "windows_x64"

## Steps to reproduce
Was running `dart test --coverage=coverage` on the winmd package, commit https://github.com/timsneath/winmd/tree/5fdd4b4d795f5adf2430cb4dfd6dad554ec76620

This does _not_ happen when running `dart test` without the coverage flag.

**Comment by timsneath** [comment] 2022-05-08 15:07
It seems to be related to having an empty test (I'd commented out some stuff) with an unused package:

```dart
@TestOn('windows')

import 'package:test/test.dart';
import 'package:winmd/winmd.dart'; // this package is unused 

void main() {
  // nothing here, just commented-out tests
}
```

Removing the winmd import seems to resolve the error. It consistently reproduces _with_ the unused package import, and consistently does not reproduce _without_ it.

**Comment by jakemac53** [comment] 2022-05-13 17:44
It seems to me like the isolate for the test has probably shut down earlier than expected? Maybe if we have no tests then it ends up exiting early. Possibly a race condition or something else?

**Comment by jakemac53** [comment] 2022-05-13 17:59
I can't repro this in the general case, so we will need to get on a windows box and debug this exact repro I think.

**Comment by incendial** [comment] 2022-05-15 19:20
Hi, got the same error report on CI (and it's not a Windows environment), https://github.com/dart-code-checker/dart-code-metrics/runs/6442860371?check_suite_focus=true#step:5:432

**Comment by jakemac53** [comment] 2022-05-16 16:19
Interesting, good to know that it isn't isolated to windows.

**Comment by incendial** [comment] 2022-05-16 16:29
jfyi, I don't know how useful this info is, but we hit this issue again on another branch CI run https://github.com/dart-code-checker/dart-code-metrics/runs/6451848785?check_suite_focus=true#step:5:144

**Comment by mraleph** [comment] 2022-05-16 18:42
I don't think anything should have changed in when an isolate group exits (that should happen when the last isolate in the group disappears - which in turns should happen when the last port is closed). /cc @aam @mkustermann to confirm no changes.

I wonder if there were some changes in the coverage package itself that are causing this? /cc @liamappelbe is the person that knows most about that package today.

**Comment by liamappelbe** [comment] 2022-05-16 19:13
> I wonder if there were some changes in the coverage package itself that are causing this? /cc @liamappelbe is the person that knows most about that package today.

Not that I'm aware of. Version 1.3.0 was published on May 11, a few days after this bug was seen, and the version before that was published in March. The only coverage change I've made related to isolate groups was 8 months ago.

It sounds like the bug was only noticed because Tim commented out some stuff in memberref_test, so it's hard to reason about exactly when the bug was introduced (or if it's always been there). Maybe the fix is just to put a try/catch around the getIsolateGroup call, to handle this exception more gracefully?

**Comment by aam** [comment] 2022-05-16 20:06
> I don't think anything should have changed in when an isolate group exits (that should happen when the last isolate in the group disappears - which in turns should happen when the last port is closed). /cc @aam @mkustermann to confirm no changes.

That's correct to the best of my knowledge.

> Was running dart test --coverage=coverage on the winmd package, commit https://github.com/timsneath/winmd/tree/5fdd4b4d795f5adf2430cb4dfd6dad554ec76620

Out of curiosity I tried this commit but was getting COR_FIELD_OFFSET errors:
```
PS C:\src\winmd> .\coverage.cmd
Building package executable...
Built test:test.
00:03 +0 -1: loading test\base_test.dart [E]
  Failed to load "test\base_test.dart":
  lib/src/com/IMetaDataImport.dart:463:13: Error: Type 'COR_FIELD_OFFSET' not found.
      Pointer<COR_FIELD_OFFSET> rgFieldOffset,
              ^^^^^^^^^^^^^^^^
```

**Comment by timsneath** [comment] 2022-05-17 02:58
> Out of curiosity I tried this commit but was getting COR_FIELD_OFFSET errors:

Can you edit the pubspec.yaml to point to win32 v2.6.0? I think this will fix you. I moved it over from win32 to winmd because this struct more properly belonged there. It's a breaking change, but the two packages are normally pinned to each other.

**Comment by aam** [comment] 2022-05-17 05:40
> > Out of curiosity I tried this commit but was getting COR_FIELD_OFFSET errors:
> 
> Can you edit the pubspec.yaml to point to win32 v2.6.0? I think this will fix you. I moved it over from win32 to winmd because this struct more properly belonged there. It's a breaking change, but the two packages are normally pinned to each other.

Aha, thanks. That worked. Am able to reproduce the failure now too.

**Comment by aam** [comment] 2022-05-17 18:22
Indeed isolates running tests exit, causing owning isolate groups to exit, all while  `_getAllCoverage` https://github.com/dart-lang/coverage/blob/master/lib/src/collect.dart#L140 iterates through all isolate groups in the vm.
It seems that multiple concurrent `_getAllCoverage` are running within the same vm during testing/coverage collection? Is that as intended?

**Comment by liamappelbe** [comment] 2022-05-17 18:31
@aam No, that's not intended. Can you try running coverage directly, rather than going through `dart test --coverage=coverage`? Maybe there's an issue with how package:test is invoking the coverage tools.

From the root dir of the package:
```
dart pub global activate coverage
dart pub global run coverage:test_with_coverage
```

**Comment by aam** [comment] 2022-05-17 21:38
@liamappelbe , when running `coverage/bin/test_with_coverage.dart` directly, the logs indicate that coverage only runs once, after all tests are done running.

**Comment by liamappelbe** [comment] 2022-05-17 21:42
Does the bug reproduce with `coverage/bin/test_with_coverage.dart`, or does it only repro with `dart test --coverage=coverage`?

**Comment by aam** [comment] 2022-05-17 21:50
I'm not able to get that crash when running `coverage/bin/test_with_coverage.dart` directly. (had to pass `--port=0` argument to run several of them in parallel).
It seems to be much more stable, but once(after running for few minutes two instances of `test_with_coverage`) I got different crash:
```
Unhandled exception:
FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#3      JsonDecoder.convert (dart:convert/json.dart:612:36)
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
#5      HitMap.parseFiles (package:coverage/src/hitmap.dart:170:28)
#6      main (file:///C:/src/coverage/bin/format_coverage.dart:66:31)
#7      main (file:///C:/src/coverage/bin/test_with_coverage.dart:194:25)
<asynchronous suspension>
```
But that seems to be something else.

**Comment by liamappelbe** [comment] 2022-05-17 21:55
Thanks Alex. Sounds like it's something about the way package:test is invoking the coverage tools then.

**Comment by jakemac53** [comment] 2022-05-26 14:12
The test package bootstraps the actual test with some other code that manages communication with the host test runner as well as lifecycle stuff like this. My _assumption_ is that is also how we ensure the isolate stays open - the isolate doesn't shut down until we explicitly shut it down due to having an open communication channel with the host runner.

**Comment by jakemac53** [comment] 2022-05-26 14:31
As far as I can tell, this is the call that would ultimately result in that connection being closed https://github.com/dart-lang/test/blob/a9d63ca7a87b6d510523e5ec5829380d4294366f/pkgs/test_core/lib/src/runner/engine.dart#L272.

One thing that is a bit suspicious here is the use of `allowRelease`, that call doesn't actually invoke the callback (afaict what actually close that connection), until a new resource is actually needed. I think this is so that we can capture any extra async errors that might come in after the tests are done running (also just an educated guess though). But it could lead to some race conditions if coverage isn't actually done collecting yet for some reason.

Ultimately need to get a debugger hooked in with the repro case though to really diagnose this.

**Comment by jakemac53** [comment] 2022-05-27 15:14
I went ahead and updated my dev environment etc on my windows box to try and debug this issue, but I am not able to reproduce it. I tried on both the latest stable and dev.

cc @timsneath how reliably does this reproduce? I tried running the tests a few times.

**Comment by incendial** [comment] 2022-06-06 17:50
Hi again, any progress on that? Getting this error from time to time on CI, kinda frustrating 😞

**Comment by nico-famedly** [comment] 2022-08-08 12:10
One way I can reproduce this fairly reliably seems to be, if I have a whole test group in a file, that gets skipped. Then there are no tests in that group and every second run times out...

**Comment by KOGI** [comment] 2022-09-14 00:47
This fails a CI build several times a day for me. It's very inconsistent, though, so I have no idea what I need to change to avoid it. I'm probably using double my build minutes for the last 2-3 weeks due to constantly re-running my build pipeline hoping it'll finish this time.

**Comment by nico-famedly** [comment] 2022-09-14 08:27
We disabled coverage in our CI now, since it simply made the CI runs too flaky.

**Comment by KOGI** [comment] 2022-09-29 19:39
Any update on this? This is absolutely destroying my CI efficiency and my build minutes bill! (not to mention my sanity)

**Comment by liamappelbe** [comment] 2022-09-29 19:43
Try updating to package:coverage v1.6.1. I wasn't able to get to the bottom of this bug, but I had to add handling for SentinelExceptions for unrelated reasons. So that may have inadvertently fixed this for you.

**Comment by KOGI** [comment] 2022-09-29 22:08
Thanks for the suggestion @liamappelbe. Unfortunately, that doesn't seem to have helped the issue. :(

**Comment by KOGI** [comment] 2022-10-27 12:14
So, I stood up a brand new repo for a new project over the last couple days and we're getting this error on 90% of builds on this one, too. :( I don't know what else to do!

**Comment by aam** [comment] 2022-11-02 17:56
> One way I can reproduce this fairly reliably seems to be, if I have a whole test group in a file, that gets skipped. Then there are no tests in that group and every second run times out...

Are you getting a timeout or unhandled exception crash?
This bug is about getting a crash, if you are experiencing something else I suggest opening a new bug to avoid confusion.
I don't think originally reported crash reproduces anymore, so this bug can be closed.

**Comment by KOGI** [comment] 2022-11-04 00:45
@aam based on several recent comments in this thread, I feel like this bug is far from being ready to close!

**Comment by aam** [comment] 2022-11-04 01:46
> @aam based on several recent comments in this thread, I feel like this bug is far from being ready to close!

Can you please clarify what exact symptoms you experience.

**Comment by mrgnhnt96** [comment] 2022-11-04 10:21
Also experiencing this issue running on Mac 

```console
[Sentinel kind: Expired, valueAsString: <expired>] from getIsolateGroup()
package:vm_service/src/vm_service.dart 1734:45        new _OutstandingRequest
package:vm_service/src/vm_service.dart 2245:21        VmService._call
package:vm_service/src/vm_service.dart 1978:7         VmService.getIsolateGroup
package:coverage/src/collect.dart 111:40              _getAllCoverage
package:coverage/src/collect.dart 79:12               collect
package:test_core/src/runner/vm/platform.dart 203:10  _gatherCoverage
package:test_core/src/runner/runner_suite.dart 79:8   RunnerSuite.gatherCoverage
package:test_core/src/runner/coverage.dart 16:18      writeCoverage
package:test_core/src/runner/engine.dart 270:36       Engine.run.<fn>.<fn>

This is an unexpected error. Please file an issue at http://github.com/dart-lang/test
with the stack trace and instructions for reproducing the error.
Unhandled exception:
[Sentinel kind: Expired, valueAsString: <expired>] from getIsolateGroup()
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1734:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2245:21)
#2      VmService.getIsolateGroup (package:vm_service/src/vm_service.dart:1978:7)
#3      _getAllCoverage (package:coverage/src/collect.dart:111:40)
<asynchronous suspension>
#4      collect (package:coverage/src/collect.dart:79:12)
<asynchronous suspension>
#5      _gatherCoverage (package:test_core/src/runner/vm/platform.dart:203:10)
<asynchronous suspension>
#6      RunnerSuite.gatherCoverage (package:test_core/src/runner/runner_suite.dart:79:8)
<asynchronous suspension>
#7      writeCoverage (package:test_core/src/runner/coverage.dart:16:18)
<asynchronous suspension>
#8      Engine.run.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/engine.dart:270:36)
<asynchronous suspension>
```

This occurred while running the following script.

```console
dart run test -r expanded --timeout 60s --coverage coverage
```

I found that if I run the script once and then again immediately upon completion that I get this error pretty consistently. If I wait a few seconds between running the script though, I found it to usually resolve the issue.

I don't have any empty tests, groups, or test files. If you'd like, you can try running my tests from [my project][1]

[1]: https://github.com/mrgnhnt96/brick_oven

**Comment by a-siva** [comment] 2022-11-04 17:31
> Also experiencing this issue running on Mac
> 
@mrgnhnt96 which version of Flutter/Dart are you using?

**Comment by mrgnhnt96** [comment] 2022-11-04 17:42
Latest stable on both, I'm AFK rn, but I'll can get you the flutter doctor logs when I get back

**Comment by a-siva** [comment] 2022-12-01 18:20
> @aam can we get a release/tag for this, pretty please? pray

A cherry pick request has been filed here https://github.com/dart-lang/sdk/issues/50491

**Comment by aam** [comment] 2022-12-01 18:29
> @aam can we get a release/tag for this, pretty please? pray

This has been available in flutter main channel since [3.6.0-1.0.pre](https://github.com/flutter/flutter/releases/tag/3.6.0-1.0.pre)

**Comment by KOGI** [comment] 2022-12-01 19:18
@aam so what version should I include in the dev_dependencies section of my pubspec.yaml?

**Comment by aam** [comment] 2022-12-01 19:21
> @aam so what version should I include in the dev_dependencies section of my pubspec.yaml?

The fix is not in a package dependency, the fix is in dart/flutter sdk itself. It can only be fixed by moving up to the version of dart/flutter sdk that has the fix(commit mentioned above https://github.com/dart-lang/test/issues/1698#issuecomment-1305838599)

**Comment by KOGI** [comment] 2022-12-01 19:32
Ahhhh, I missed that. TY!

**Comment by natebosch** [comment] 2023-03-23 00:06
Closing since it looks like everything has been resolved upstream in the SDK.

**Closed by natebosch** 2023-03-23 00:06 UTC
Labels: bug
