### ISSUE TITLE
Dartium and content-shell fail to close after tests are complete.

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/test#88] opened 2015-04-22 20:50 UTC
When running tests with either dartium or content-shell, the process hangs after the tests complete and the browser remains open, requiring a ctrl+c to kill them. Running tests in any of the other browsers (chrome, firefox, safari) works as expected.

For reference, the commands I'm using:

```
pub run test:test test/browser -p dartium
```
```
pub run test:test test/browser -p content-shell
```

**Comment by kevmoo** [comment] 2015-04-22 20:51
When version of test are you running?
Which OS?

**Comment by zoechi** [comment] 2015-04-22 20:58
Works fine for me on Linux so far.

**Comment by nex3** [comment] 2015-04-22 21:06
Also what versions of Dartium and content_shell?

**Comment by evanweible-wf** [comment] 2015-04-22 21:12
Mac OS: 10.10.3
test: 0.12.0-beta.10
dartium: 39.0.2171.99
content-shell: 19.77.34.5

**Comment by nex3** [comment] 2015-04-22 21:18
That's a very old content_shell, so that's not really expected to work. I'm not sure why Dartium is failing. Do you see any output on the dev console?

**Comment by evanweible-wf** [comment] 2015-04-22 21:28
Not sure how best to upgrade content-shell, I was under the impression that installing dartium via brew would also install content-shell. Any tips there?

As for the dev console output, I see an expected logging statement from one of my tests but nothing else.

**Comment by nex3** [comment] 2015-04-22 21:33
@kevmoo can you reproduce this on your mac?

**Comment by kevmoo** [comment] 2015-04-23 17:12
Nope. Works great for me.

@evanweible-wf You'll want to get the latest `content_shell` – which version of Dart are you running?

You can grab it here for the latest dev release: https://gsdview.appspot.com/dart-archive/channels/dev/release/45311/dartium/

**Comment by evanweible-wf** [comment] 2015-04-23 18:49
I'm running Dart 1.9.3. I downloaded dartium and content_shell from the link you posted, but I'm still seeing the issue in both. Little confused though, because even after downloading content_shell from that source, opening it, and checking Content Shell > About Content Shell, it still lists the version as 19.77.34.5 (34.5), which you said was very old.

**Comment by nex3** [comment] 2015-04-23 19:33
I'm closing this; since we can't reproduce it, I don't think there's much more we can do. Sorry we couldn't be more helpful :disappointed:.

> Little confused though, because even after downloading content_shell from that source, opening it, and checking Content Shell > About Content Shell, it still lists the version as 19.77.34.5 (34.5), which you said was very old.

It may be that the version number doesn't match up with Chrome's?

**Closed by nex3** 2015-04-23 19:33 UTC
Labels: bug, needs info

**Comment by kevmoo** [comment] 2015-04-23 20:07
@evanweible-wf Could you try 1.10-dev?

If you install the homebrew link, you can use `--dev`

**Comment by evanweible-wf** [comment] 2015-04-23 20:12
Yeah I'll give that a shot later today.
