### ISSUE TITLE
Support for xunit test reporter

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/test#95] opened 2015-04-28 04:31 UTC
We'd like to be able to get test results for vm/browser tests in [xunit](https://github.com/xunit/xunit) format. In general, it would be nice to be able to easily create/provide a custom test reporter.

**Comment by Fox32** [comment] 2015-04-28 08:50
Related: #12  #11

**Comment by nex3** [comment] 2015-04-28 17:02
Duplicate of #12.

**Closed by nex3** 2015-04-28 17:02 UTC
