### ISSUE TITLE
Global tear-down function

### ISSUE THREAD

**Issue by zanderso** [dart-lang/test#333] opened 2015-08-31 16:31 UTC
In the Mojo embedder, we need to ensure that the very last action taken by a program is to close the handle to the Mojo shell. Currently, we are using a work-around here:

https://github.com/domokit/mojo/blob/master/mojo/public/dart/mojo_apptest/lib/apptest.dart

That is, a dummy test ('TERMINATE SHELL CONNECTION') is set up to call close(). This creates a race between the closing of the shell handle, and the test harness printing "All tests passed!", which the Mojo test scripts flake on. We can queue up the call to close() in a Timer, but there's no guarantee that this will not race and flake, as well.

To avoid this problem, we'd like to be able to give the test harness a callback to run sometime after printing "All tests passed!", or whatever its final message is. It's unclear how Mojo and Mojo SDK consumers will write non-flaky tests with the test harness without this feature, so I hope you don't mind if I mark this as high-priority.

@emembrives @tonygentilcore

**Comment by nex3** [comment] 2015-08-31 20:04
Duplicate of #33.

**Closed by nex3** 2015-08-31 20:04 UTC
Labels: enhancement, high priority

**Comment by tonygentilcore** [comment] 2015-09-01 14:14
Thanks for the quick response. Just want to make sure I follow -- this is #33 and it's #18. Is there a rough idea for how #18's API will look? Would it be helpful to add this use case directly to that bug?

**Comment by nex3** [comment] 2015-09-01 20:09
I think the API is pretty straightforward—there would be group-scoped `setUpAll` and `tearDownAll` functions that you'd use like this:

```dart
void main() {
  setUpAll(() {
    // Code to run before any tests have started.
  });

  tearDownAll(() {
    // Code to run after all tests have finished.
  });

  // Define tests here.
}
```

**Comment by tonygentilcore** [comment] 2015-09-01 21:38
Excellent, looking forward to it :)
