### ISSUE TITLE
There should be a way to hide successful tests

### ISSUE THREAD

**Issue by dikmax** [dart-lang/test#378] opened 2015-12-27 10:05 UTC
I think something like `--quiet` option will be sufficient. 

Right not progress indicator updated on every completed test, doesn't matter successful or not. This leads to overwhelming console output on big test suites. And this could lead to fail on CI servers. 
For example Travis build  fails to finish if console output size is bigger than 4 Mb.

**Comment by zoechi** [comment] 2015-12-27 10:15
I think you can already use custom reporters to adjust the output to your demands https://github.com/dart-lang/test/blob/master/json_reporter.md

**Comment by nex3** [comment] 2016-01-04 20:54
Custom reporters aren't currently supported, but they are planned. This will be a good use-case for them, though, so I'm going to mark it as a duplicate of #12.

**Closed by nex3** 2016-01-04 20:54 UTC
