### ISSUE TITLE
Timed out browser tests.

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#106] opened 2015-05-06 20:35 UTC
I get a lot of 
`Failed to load "test/all_icons_test.dart": Timed out waiting for the test suite to connect on Chrome.`
` Failed to load "test/simple_test.dart": Timed out waiting for the test suite to connect on Dartium.`
...

When I use `--pub-serve=xxxx` to have a warm instance it works sometimes with Chrome on subsequent attempts. I wasn't able to successfully run a test with Firefox or Phantom.js this way. 
It even often fails with Dartium on first attempt.

If I only run a single test file it's more likely to succeed.
https://github.com/bwu-dart/bwu_fontawesome_iconset_svg/tree/master/test

**Comment by nex3** [comment] 2015-05-06 20:42
Duplicate of #102. It looks like we should substantially increase the timeout here, and maybe limit the number of concurrent loads for the same browser.

**Closed by nex3** 2015-05-06 20:42 UTC
