### ISSUE TITLE
Add the ability to rerun tests that failed last

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/test#493] opened 2016-11-16 04:26 UTC
i.e. `pub run test --rerun`

Obviously you'd need to keep state of what failed last run, but that's probably fine?

It probably could be implemented as a separate runner using the machine readable output format and `--plain-name` multiple times - but there isn't actually a way to say "match this whole string, not substring" - so it won't always work.

**Comment by nex3** [comment] 2016-11-16 20:41
Duplicate of #329.

**Closed by nex3** 2016-11-16 20:41 UTC
