### ISSUE TITLE
browser-test with dash in its name breaks test (e.g. data-table_test.[dart | html])

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/test#884] opened 2018-06-15 09:43 UTC
I have a UI test where the test files are named `data-table_test.dart` and `data-table_test.html`

If I run the test via `webdev serve --no-release test` Chrome shows me `Uncaught ReferenceError: table_test is not defined` If I rename the files to datatable_test.* it works

Dart VM version: 2.0.0-dev.63.0 (Fri Jun 15 00:42:43 2018 +0200) on "macos_x64"

![capturfiles-20180615_103133](https://user-images.githubusercontent.com/116654/41461765-ee5d13c4-7090-11e8-9338-21cdeb08ea5d.png)

**Comment by jakemac53** [comment] 2018-06-15 13:56
Duplicate of https://github.com/dart-lang/build/issues/1523, this will be fixed in the next build_web_compilers release

**Closed** 2018-06-15 13:56 UTC
