### ISSUE TITLE
--precompiled vm tests can't easily read from the precompiled directory

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#805] opened 2018-04-10 18:28 UTC
The working directory of the isolate is the same as the main dart process, meaning the root package directory. If you want to read generated files (goldens, etc), you need to know where those files are generated.

Ideally we would either be able to change the working directory or at least expose a path to the precompiled directory for tests to read from.

**Comment by natebosch** [comment] 2023-02-22 01:50
I think we should consider this a duplicate of https://github.com/dart-lang/test/issues/110

I think if we had an API for reading files from a standard location we could make it work for precompiled tests automatically. We could even make it work to have multiple search directories for the files, and read from either the precompiled output or package source.

**Closed by natebosch** 2023-02-22 01:50 UTC
Labels: duplicate, enhancement
