### ISSUE TITLE
Absolute folder path filters trigger "no test found"

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/test#1667] opened 2022-02-11 12:08 UTC
It seems like if `dart test folderPath` is executed an absolute path instead of a relative path, then `dart test` will somehow fail to execute the tests

Example:

```
$ pwd
/Users/remirousselet/dev/invertase/fest/packages/spec_cli

$ dart test .
< works just fine > 

$ dart test /Users/remirousselet/dev/invertase/fest/packages/spec_cli
No tests ran.
No tests were found.
```

**Comment by jakemac53** [comment] 2022-02-14 16:54
This seems to work fine for me on linux, can you clarify what platform you are on or provide any additional info you think might be relevant?

**Comment by rrousselGit** [comment] 2022-02-14 16:55
It happened on Mac for me.

I'm not exactly sure what else to say

**Comment by jakemac53** [comment] 2022-02-14 16:56
Ok, I don't have a mac to test this on, but I think @natebosch does. Although I would be very surprised if it works on linux but not mac...

**Comment by rrousselGit** [comment] 2022-02-14 17:35
Haha, I'm not quite sure either.

In any case, since this was triggered by my custom test renderer, I used a workaround and converted paths to relative ones.

**Comment by natebosch** [comment] 2022-02-14 19:12
I can't reproduce this behavior. I'm on mac with the latest stable SDK (`2.16.1`) and latest `test` (`1.20.1`)

I get the same results whether I run with no argument, `.`, or an absolute path to the directory with or without a trailing `/`.


```
[11:08]»  dart test
Building package executable... (7.7s)
Built test:test.
00:04 +394: All tests passed!
[11:08]»  dart test .
00:03 +394: All tests passed!
[11:08]»  dart test /Users/nbosch/repos/stream_transform
00:03 +394: All tests passed!
[11:08]»  dart test /Users/nbosch/repos/stream_transform/
00:03 +394: All tests passed!
```

**Comment by jakemac53** [comment] 2022-02-14 19:17
I am going to close this as not reproducible for now, if you can figure out a way to reproduce it we can take another look

**Comment by rrousselGit** [comment] 2022-02-14 19:30
If that helps here's my dart version

```
Dart SDK version: 2.16.0-144.0.dev (dev) (Thu Dec 30 11:53:00 2021 -0800) on "macos_x64"

```

on macos 12.2:


Here's a video too:


https://user-images.githubusercontent.com/20165741/153932767-31ae9b7d-280c-4b7e-9ec9-1bb29000a34e.mov

**Comment by natebosch** [comment] 2022-02-14 19:44
We must still have some code treating `packages` as a special directory name. I can repro this if I move my packages into a directory with `/packages/` somewhere on the path.

**Comment by rrousselGit** [comment] 2022-02-14 19:45
Upgrading Dart to `2.17.0-104.0.dev` and `test` to `1.20.1` (from ` 1.17.12`) changed nothing by the way.

I created a brand new project, and for some reason with that project, absolute paths works.
It seems related to projects with a packages folder from my tests

**Comment by natebosch** [comment] 2022-02-14 19:47
https://github.com/dart-lang/test/blob/5bbe1a893935ef20fbe8250ef804f863f4efb5a3/pkgs/test_core/lib/src/runner/loader.dart#L145

**Closed** 2022-02-14 21:11 UTC
Labels: cannot reproduce
