### ISSUE TITLE
Add regression test for DDC stack traces

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/test#677] opened 2017-08-28 19:39 UTC
We've noticed internally that stack traces provided by pkg/test are much worse in DDC.

Here's a test case from AngularDart, both failing in Dartium and DDC respectively:

## Dartium

```
Injector .slowReflective should support resolveAndCreateChild [E]                    
  Expected: C:<C: newC>
    Actual: C:<C: oldC>
  Expected an old "C" binding
  
  package:test              expect
  injector_test.dart 216:9  main.<fn>.<fn>.<fn>
```

## DDC (Chrome)

```
Injector .slowReflective should support resolveAndCreateChild [E]                    
  Expected: C:<C: newC>
    Actual: C:<C: oldC>
  Expected an old "C" binding
  
  dart:_runtime                                   library.library.dart.throw
  packages/test/src/frontend/expect.dart 164:30   library.library.src._frontend._expect.fail
  packages/test/src/frontend/expect.dart 158:3    library.library.src._frontend._expect._expect
  packages/test/src/frontend/expect.dart 68:3     library.library.src._frontend._expect.expect
  ../di.injector_test_library.js 257:33           .test.dart.fn
  packages/test/src/backend/declarer.dart 148:15  dart.library.library.src._backend._declarer.Declarer._.<fn>
```

Major differences:

* DDC version of the code never refers to my actual Dart code (I didn't write inejctor_test_library.js)
* Includes method calls I never made ("_runtime")
* Includes a bunch of cruft (expect, declarer) that doesn't existing in the Dartium version

**Comment by kevmoo** [comment] 2017-08-28 19:51
There was some discussion that maybe Chrome 60 broke things here, right? @vsmenon

**Comment by vsmenon** [comment] 2017-08-28 19:53
@alan-knight 

I think it was actually sources being properly refreshed in the browser dev tools.

**Comment by vsmenon** [comment] 2017-08-28 19:58
BTW, per the original bug, I suspect we need to fix `package:stack_trace` to better parse JS / DDC traces and filter extra frames:

https://github.com/dart-lang/stack_trace/blob/master/lib/src/frame.dart

**Comment by grouma** [comment] 2017-08-28 20:01
The filter logic on our end is here: https://github.com/dart-lang/test/blob/960bbe6a5917c66f87d770b992ba15e243d0c1bd/lib/src/frontend/test_chain.dart#L42.

I think the issue is that these are no longer package imports but just relative path imports e.g. packages/test/src and thus the package isn't correctly getting assigned. It does appear to be a chrome or DDC bug depending on how the stack trace is captured.

**Comment by natebosch** [comment] 2017-08-28 20:52
This could also have to do with some internal changes in how the package map is resolved. I think we should do some further digging around that.

**Comment by grouma** [comment] 2018-06-15 18:03
Closing as build_web_compilers has a regression test and DDC is only supported from that package.

**Closed by grouma** 2018-06-15 18:03 UTC
Labels: enhancement
