### ISSUE TITLE
`pub run test` slow initialization.

### ISSUE THREAD

**Issue by dikmax** [dart-lang/test#457] opened 2016-09-01 13:07 UTC
`pub run test` initializes really slow.

When I write:

```bash
pub run test -p vm test/library_test.dart
```

runner waits around 25 seconds and then run everything in 7 seconds.

At the same time, writing

```bash
dart test/library_test.dart
```

will end in just 4 seconds.

I don't mind a bit slower execution, but having to wait half of minute is too much, and this time tends to increase as I add more tests.

You can check everything yourself on [dikmax/md_proc](https://github.com/dikmax/md_proc/tree/rewrite) branch `rewrite`.

**Comment by nex3** [comment] 2016-09-01 19:13
I can reproduce this. That's very strange, and I'm guessing it's ultimately a VM or Isolate issue. I'm not sure I'll have a chance to debug this before I go on vacation, but I'll make sure to check it out when I get back.

**Comment by nex3** [comment] 2016-09-28 21:20
Looks like it's actually transferring stack traces between isolates that's causing the issue. We don't actually use the full traces, so I think we can pretty easily avoid the vast majority of the overhead.

**Comment by nex3** [comment] 2016-09-29 20:08
Turns out that's not quite correct either. The problem is *collecting* the stack traces, not transferring them. Just calling `new StackTrace.current().toString()` is very expensive when done across ten thousand tests. I had been trying to just send a single frame's worth of information across isolates, but that won't work either. We can disable collection entirely when users aren't using the JSON reporter, but it'll still be extremely slow when run from IntelliJ.

/cc @jwren, @devoncarew, @alexander-doroshko for the heads-up about potential perf issues

**Comment by devoncarew** [comment] 2016-09-29 20:13
@a-siva, do you have a sense for where the expense is in collecting stack traces?

@nex3, the issue is that at each test definition, we're creating a stack trace in order to record the location of the test, is that correct? And, this is being done enough times to materially delay the start of the test runner?

**Comment by nex3** [comment] 2016-09-29 20:17
> @nex3, the issue is that at each test definition, we're creating a stack trace in order to record the location of the test, is that correct? And, this is being done enough times to materially delay the start of the test runner?

That's right—it takes about 30s to collect traces for about 11,000 tests, so about 2.7ms per stack.

**Comment by devoncarew** [comment] 2016-09-29 20:22
That is a lot of tests!

**Comment by nex3** [comment] 2016-09-29 20:28
That's true, but it's not outside the realm of possibility, especially if (as in this case) they're auto-generated from some third-party suite of examples.

**Closed** 2016-09-30 00:09 UTC
Labels: bug
