### ISSUE TITLE
using `this.msg` as the name when defining a property of a class makes test hang

### ISSUE THREAD

**Issue by whesse** [dart-lang/test#389] opened 2016-01-27 09:46 UTC
I have copied the contents of a SDK issue here, since it seems to be specific to the test package:
The original issue is https://github.com/dart-lang/sdk/issues/25585 .
Issue https://github.com/dart-lang/sdk/issues/25584 is also related.

hackst8r commented 17 hours ago
import 'package:test/test.dart' ;

/**

PROBLEM
Exposed by using this.msg as the name when defining a property of a class .

$ dart --version
Dart VM version: 1.13.2 (Tue Jan  5 06:40:05 2016) on "linux_ia32"
SYMPTOM
when attempting to run this test , the test runner get's caught in an infinite loop and must be interrupted with ^C^C .

sample output from test runner :

00:06 +0: test/test_aaaa_test.dart: use this.msg as the name when defining a property of a class   ^C
Waiting for current test(s) to finish.
Press Control-C again to terminate immediately.
^C
shell returned 254
EXPECTATION
dart should emit a syntax error instead of the current confusing and hard to track down behaviour
AUTHOR
hackst8r
**/

void main ()
{
    test ("use this.msg as the name when defining a property of a class", () => new TEST ()) ;
}

class TEST
{
    TEST ()
    {
        new FOO ('hello') ;
    }
}

class FOO
{
    String this.msg ; // - oops ! s/b : `String msg`

    FOO (String this.msg)
    {
    }
}
￼
 ￼ Collaborator
lrhn commented 22 minutes ago
The syntax causes a syntax error in my Dart VM (1.14.0), as well as in dart2js and the Dart analyzer.

@nex3
@lrhn 
@hackst8r

Is this only caused by the test runner hanging?

**Comment by nex3** [comment] 2016-01-27 21:53
This is a duplicate of #290. The short version of that issue is that the VM doesn't catch some classes of syntax errors when the isolate spawns, so when they're reached they crash the isolate, which breaks `test`'s messaging. dart-lang/sdk#23684 is tracking a fix for the underlying issue of uncatchable syntax errors.

**Closed by nex3** 2016-01-27 21:53 UTC
Labels: bug

**Comment by hackst8r** [comment] 2016-01-28 16:24
partial workaround :

- it is hard to debug these hidden syntax errors.
- as a workaround until the underlying isolate problem is fixed use `dart` to directly run the test script , revealing the syntax errors :

```
$ dart test/test_aaaa_test.dart
```

**Comment by kevmoo** [comment] 2016-09-16 19:44
FYI: Fixed https://github.com/dart-lang/sdk/issues/23684
