### ISSUE TITLE
Only run specified tests (implicitly skipping all other tests) feature

### ISSUE THREAD

**Issue by hoylen** [dart-lang/test#382] opened 2016-01-13 02:13 UTC
Provide a feature to explicitly indicate which tests (or groups) to be run, and every other test/group are implicitly skipped.

Currently there is a "skip" feature, but no run-only-these-tests feature.

For example, if you had a Dart file containing ten tests and one of them is failing, in debugging you want to run that one test while skipping the other nine. Currently, you would have to add nine "skip" parameters to do that. It would be simpler to add one line to indicate which test you want to run.

**Comment by nex3** [comment] 2016-01-13 02:32
This is a duplicate of #127. The short answer is to use the `--name` parameter or tagging for this; for the long answer, see that issue.

**Closed by nex3** 2016-01-13 02:32 UTC
