### ISSUE TITLE
Support for node platform with --precompiled flag

### ISSUE THREAD

**Issue by pulyaevskiy** [dart-lang/test#766] opened 2018-02-14 18:57 UTC
I was trying to get `build_runner` to build and run tests in [node_interop](https://github.com/pulyaevskiy/node-interop/tree/master/node_interop) package but `pub run test --precompiled` doesn't seem to support node platform yet. It always falls back to compile the source itself.

I have created [build_node_compilers](https://pub.dartlang.org/packages/build_node_compilers) package which produces Node-compatible output. If I just build my tests and run them manually (e.g. `node build/test/some_test.dart.js`) it works fine. But it'd be really great to have it running through the standard tooling.

**Comment by nex3** [comment] 2018-02-14 20:14
`--precompiled` is *not* an official part of the test runner's API. It was added for Google-internal tooling, and any use of it outside of that context is unsupported. As such, I don't want to expand the set of things it happens to support and thereby encourage more people to use it.

That said, I'm definitely interested in getting the full matrix of build/DDC/platform configurations, and I have some experimental work in progress to that end that will hopefully come out on the sooner end.

**Comment by pulyaevskiy** [comment] 2018-02-14 20:23
That makes sense, thanks for quick response. If there is anywhere I can click "Subscribe" to follow progress on this front please let me know!

**Comment by nex3** [comment] 2018-02-14 20:46
I'll try to remember to post something here once code reviews start going up.

Out of curiosity, are you interested in build mostly for the speed improvements of DDC or because you're running tests against generated code?

**Comment by pulyaevskiy** [comment] 2018-02-14 20:54
Mostly to validate that my JS bindings work in both DDC and dart2js (as well as Dart code using these bindings). There are differences in how JS interop is interpreted by both compilers, the same code can run perfectly fine in dart2js but fail badly in DDC and vice versa.

So I needed a way to run tests with both of them. For now I'm just gonna use a little shell script as a workaround:

```sh
#!/bin/sh

pub run build_runner build --output=build/

for filename in test/*_test.dart; do
    node "build/$filename.js"
done
```

**Comment by jakemac53** [comment] 2018-04-06 21:05
I am going to see if I can tackle this - we are changing the semantics and support level for --precompiled so it can be used reliably with build_runner for all scenarios.

**Comment by jakemac53** [comment] 2018-04-10 20:25
@pulyaevskiy this is published now if you want to give it a shot! Please file issues if it doesn't work for you :).

**Comment by jakemac53** [comment] 2018-04-10 21:09
hmm I checkout out the node_interop issue and I am seeing a couple problems, sent out https://github.com/dart-lang/test/pull/807 which resolves the first issue.

**Comment by pulyaevskiy** [comment] 2018-04-10 21:10
Thanks @jakemac53 ! This is great. Just tried a quick run with new versions and it almost works. I'm getting errors like:

```
compiling test/console_test.dart [E]
  Failed to load "test/console_test.dart": Cannot open file, path = 'build/console_test.dart.node_test.dart.js.map' (OS Error: No such file or directory, errno = 2)
```

I tried to run test with `--precompiled build/test/` but then it couldn't find `.packages` file. 

Might need to fix something in build_node_compilers, not sure yet.

**Comment by jakemac53** [comment] 2018-04-10 21:12
Yep - that issue should be fixed with my latest pr, can you add a dependency override on that branch and try?

Should look roughly like this:
```
dependency_overrides:
  test:
    git:
      url: https://github.com/dart-lang/test
      ref: node-fixes
```

**Comment by pulyaevskiy** [comment] 2018-04-10 21:12
Sure, checking it now

**Comment by jakemac53** [comment] 2018-04-10 21:13
I am getting a weird permissions issue with Node locally - not sure what exactly the problem is though so I am curious if you get the same thing.

**Comment by pulyaevskiy** [comment] 2018-04-10 21:14
It looks better now:

```
Cannot open file, path = 'build/test/util_test.dart.node_test.dart.js.map' (OS Error: No such file or directory, errno = 2)
```

This maybe something I should fix in `build_node_compilers`? Probably filenames don't match?

**Comment by jakemac53** [comment] 2018-04-10 21:18
You probably just need to add a dependency on `build_test`

**Comment by pulyaevskiy** [comment] 2018-04-10 21:27
Yeah, added `build_test` and the error went away.

Now I'm getting some DDC/strong mode warnings with streams. And for dart2js it ran successfully except it only executed 3 test files of total 8 in `test/` folder.

**Comment by jakemac53** [comment] 2018-04-10 21:31
Ok - getting somewhere! I think the strong mode errors are legit errors that need to be fixed in the node test runner bootstrapping code.

**Comment by pulyaevskiy** [comment] 2018-04-10 21:32
Oh, I take it back. Looks like all tests ran it's just output is somewhat weird

**Comment by jakemac53** [comment] 2018-04-10 21:46
What was weird about the output?

**Comment by pulyaevskiy** [comment] 2018-04-10 21:52
If I use `-r expanded` each run prints results in different order and always skipping some of the tests. E.g.:

```
00:00 +0: compiling test/console_test.dart
00:00 +0: test/child_process_test.dart: child_process exec successful
00:00 +1: test/child_process_test.dart: child_process exec successful
00:00 +2: test/child_process_test.dart: child_process exec successful
00:00 +3: test/timers_test.dart: Timers setImmediate
00:00 +4: test/buffer_test.dart: Buffer from array
00:00 +5: test/console_test.dart: console integration
00:00 +5: test/buffer_test.dart: Buffer keys()
  Skip: Broken in dart2js
00:00 +5 ~1: test/console_test.dart: console integration
00:00 +5 ~1: test/buffer_test.dart: Buffer values()
  Skip: Broken in dart2js
00:00 +5 ~2: test/console_test.dart: console integration
00:00 +5 ~2: test/buffer_test.dart: Buffer entries()
  Skip: Broken in dart2js
00:00 +5 ~3: test/console_test.dart: console integration
00:00 +6 ~3: test/promises_test.dart: promiseToFuture
00:00 +7 ~3: test/util_test.dart: dartify it handles js primitives
00:00 +8 ~3: test/util_test.dart: dartify it handles js primitives
00:00 +9 ~3: test/util_test.dart: dartify it handles js primitives
00:00 +10 ~3: test/util_test.dart: dartify it handles js primitives
00:00 +11 ~3: test/promises_test.dart: reject a Future
00:00 +12 ~3: test/util_test.dart: dartify it handles POJOs
00:00 +13 ~3: test/util_test.dart: dartify it handles arrays
00:00 +14 ~3: test/util_test.dart: dartify it DOES handle JS functions with properties
00:00 +15 ~3: test/util_test.dart: dartify it handles objects with prototypes
00:00 +16 ~3: All tests passed!
```

Here it's missing `stream_test.dart`, for instance.

**Comment by pulyaevskiy** [comment] 2018-04-10 21:54
I'm sure it runs all the tests as numbers in the end match, so it's probably something unrelated. I think some time ago I saw similar issues with regular tests in Dart VM and it had something to do with how test package runs tests in parallel.

**Comment by jakemac53** [comment] 2018-04-10 21:59
> I'm sure it runs all the tests as numbers in the end match, so it's probably something unrelated. I think some time ago I saw similar issues with regular tests in Dart VM and it had something to do with how test package runs tests in parallel.

Ya I think you are right, the order I think is intentionally not consistent but the fact that the names are wrong is pretty weird.

**Comment by jakemac53** [comment] 2018-04-10 22:04
Ok, merged that PR but going to try and fix the runtime error for DDC before I publish a new version.

**Comment by jakemac53** [comment] 2018-04-16 19:02
https://github.com/dart-lang/stream_channel/pull/18 was one of the issues

**Comment by jakemac53** [comment] 2018-04-17 14:59
@pulyaevskiy can you try now with a dependency override on master? You will also need to pub upgrade to get the latest stream_channel.

**Comment by pulyaevskiy** [comment] 2018-04-17 16:30
Checking this now. Will update in a few.

**Comment by pulyaevskiy** [comment] 2018-04-17 16:42
Everything works great as far as I can tell. I ran tests in node_interop, node_io and node_http packages with both dartdevc and dart2js precompiled sources and there was no issues.

So cool!

One question: I noticed in #811 we drop support for Dart 1 and it's only a patch version bump on this package. Shouldn't it at least go to `0.13.0`? Seems kind of like a major update, but regardless asking just out of curiosity.

**Comment by natebosch** [comment] 2018-04-17 16:46
> we drop support for Dart 1 and it's only a patch version bump on this package.

yes, the "breaking" change is already managed by pub so you can't version solve to an incompatible version of package:test.

**Comment by pulyaevskiy** [comment] 2018-04-17 16:52
Ah, right, so Pub would only consider versions with appropriate SDK constraint when solving? Makes sense, thanks for explanation!

**Comment by jakemac53** [comment] 2018-04-17 17:39
Yup! Glad to hear it works we should get this published pretty soon.

**Comment by jakemac53** [comment] 2018-04-17 17:43
Closing as this is just waiting on a release

**Closed by jakemac53** 2018-04-17 17:43 UTC
