### ISSUE TITLE
Support hybrid (browser + custom Dart server) tests

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#330] opened 2015-08-25 23:02 UTC
Sometimes you'd like to hit custom server code (written in Dart) from a browser test.

See pkg/http as an example.

**Comment by nex3** [comment] 2015-08-25 23:26
The example Kevin is referring to is [this one](https://github.com/dart-lang/http/blob/master/test/html/client_test.dart), where the test relies on the old `test.dart` behavior of automatically starting up an echo server.

**Comment by ErikGrimes** [comment] 2015-10-05 15:24
More generally, I'd like support for setup that occurs outside the browser.  This way I could spin up a set of Docker containers, a Dart server, or whatever else I need to setup a test for the browser test.

**Comment by kevmoo** [comment] 2015-10-05 16:26
@ErikGrimes oooo – I like that scenario. I hit it often myself.

Keep in mind "custom server code" is anything you can run with `dart:io`, which includes starting/stopping processes

**Comment by zoechi** [comment] 2015-10-05 17:40
I use grinder to run custom servers and https://pub.dartlang.org/packages/bwu_docker to run Docker containers before running `pub run test`

**Comment by ErikGrimes** [comment] 2015-10-06 15:22
@kevmoo Ahh, for some reason my brain translated custom server code to Dart only scripts!  Are you open to PR's for this?  A relatively straightforward approach would be to mimic the Process api.

**Comment by nex3** [comment] 2015-10-06 20:40
I don't think we're going to be able to design a satisfactory API here without some sort of plugin infrastructure being exposed. I want to sit on it for now.

**Comment by nex3** [comment] 2016-09-30 01:21
Closing this as a duplicate of #109.

**Closed by nex3** 2016-09-30 01:21 UTC
Labels: Customer: bolt2, enhancement
