### ISSUE TITLE
package:test should have a way to collect coverage for VM tests

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/test#983] opened 2019-02-11 18:14 UTC
_From @Hixie on February 11, 2019 18:0_

The `flutter` tool has a bunch of tests. Currently we have no good way to collect coverage to determine what lines in the tool are covered and what lines are not.

Ideally we would be able to run something like `pub run test --coverage` and get out a single `lcov.info` file that describes coverage of the tool.

_Copied from original issue: dart-lang/sdk#35910_

**Comment by vsmenon** [comment] 2019-02-11 18:14
fyi - @grouma

**Comment by cbracken** [comment] 2019-04-09 05:10
Likely dupe of #36 (please re-open if not).

**Closed by cbracken** 2019-04-09 05:10 UTC
