### ISSUE TITLE
test uses ANSI codes even when terminal isn't ANSI-aware

### ISSUE THREAD

**Issue by Hixie** [dart-lang/test#336] opened 2015-09-08 20:16 UTC
For example, the Emacs *compilation* buffer isn't ANSI-aware, so the output looks like this:

```
01:24 ^[[32m+0^[[0m: ^[[1m^[[1;30mloading test/widget/dismissing_test.dart^[[0m^[[0m
```

**Comment by nex3** [comment] 2015-09-08 20:36
Duplicate of #19.

**Closed by nex3** 2015-09-08 20:36 UTC
