### ISSUE TITLE
Don't print colors when ANSI codes are not supported

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#19] opened 2015-02-21 15:17 UTC
This is how the output looks like in WebStorm debug console:

```
debug:55618 --break-at-isolate-spawn --enable-vm-service:40572 --trace_service_pause_events /tmp/jetbrains_unit_config.dart
Testing started at 3:55 PM ...
Observatory listening on http://127.0.0.1:40572
00:00 [32m+0[0m[31m -1[0m: bwu_datastore_connection.test.model basic[0m                                              
  type '() => Entity' is not a subtype of type 'Entity' of 'value'.
  dart:core         List.addAll
  model.dart 29:24  main.<fn>.<fn>
  dart:isolate      _RawReceivePortImpl._handleMessage

00:00 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m                                                                     

Process finished with exit code 0
```

Other packages run into this as well. `pub` itself is one of these where it works well.
see also
- http://dartbug.com/21337
- http://dartbug.com/15304

**Comment by nex3** [comment] 2015-02-23 20:07
This is very difficult in full generality. The best way to detect this is to use [`stdioType`](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:io#id_stdioType), but that relies on having an accurate view of the process's IO streams. However, [`pub run` spawns its executables as subprocesses](https://code.google.com/p/dart/issues/detail?id=21821) and Dart doesn't provide any means of directly reassigning their IO streams to the parent process's IO streams, so they get an incorrect view. This in turn is blocked on [several](https://code.google.com/p/dart/issues/detail?id=20828) [core library issues](https://code.google.com/p/dart/issues/detail?id=21791). So in general, this is blocked.

What we should do in the short term is support a `--[no]-color` flag.

**Comment by zoechi** [comment] 2015-02-24 07:10
Why does it work in pub? When I run it in a shell which supports ANSI codes it's colored otherwise it's without color but also doesn't print the ANSI codes.

**Comment by nex3** [comment] 2015-02-24 18:51
Pub isn't run inside pub :wink:. It's possible for Dart programs to detect whether it's safe to use colors using `stdioType`; the problem is that this relies on having access to the real underlying stdio objects. When pub starts a subprocess, Dart doesn't provide any way of giving that process access to the parent's stdio, and thus the detection fails in the subprocess.

**Comment by zoechi** [comment] 2015-02-24 19:20
I see. Thanks for the explanation!

**Comment by Fox32** [comment] 2015-04-02 15:47
If I run my test file without the test runner from Dart Editor I would also not expect it to use ANSI codes (at least on Windows).

**Comment by nex3** [comment] 2015-04-02 19:02
@Fox32 There's no way of telling whether we're running via `pub run` or not. For now, the best solution is to just pass `--no-color` explicitly when color isn't desired.

**Comment by zoechi** [comment] 2015-04-09 10:03
I haven't found a way to pass `--no-color` when the test is executed without the test  runner. (`dart test/my_test.dart`

**Comment by nex3** [comment] 2015-04-09 18:20
That's correct. Unfortunately, there's no global way to access command-line flags ([issue 22466](https://code.google.com/p/dart/issues/detail?id=22466)), so the `test` package can't use them when the script is run directly.

In general, you should think of running a script directly as a handy shortcut when working from the terminal. There are a lot of things it won't be able to support: not just colors, but configurations, annotations, and so forth. The official way to run a test is via `pub run test`, and that's how you should (for example) configure your editor to do so.

**Comment by zoechi** [comment] 2015-04-09 18:38
This is inconvenient during development because this way debugging isn't supported. There is an open issue about debugging but I have no idea how this could work with pub run.

**Comment by nex3** [comment] 2015-04-09 18:44
[Issue 21791](https://code.google.com/p/dart/issues/detail?id=21791) will allow us to spin up test isolates with debugging ports open. For now, though, debugging is not officially supported; you're welcome to use it with `dart path/to/script`, but be aware that you're off the golden path at that point.

**Comment by zoechi** [comment] 2015-04-10 17:05
Good to know

**Comment by Hixie** [comment] 2015-09-08 20:53
You should be able to just look at the TERM environment variable to determine the current state of the console.

**Comment by nex3** [comment] 2015-09-08 21:03
Accurately parsing `TERM` or `TERMCAP` is a lot of work, and it's easy for environment variables to flow into subprocesses and so forth and compromise the accuracy of that logic.

**Comment by Hixie** [comment] 2015-09-08 21:22
It's the way e.g. `ls` works.

I don't see how anything else is going to work. How could e.g. a build script know to pass --no-color? Someone at some point is going to have to examine the terminal capabilities, since not everyone is going to be running the build scripts in the same environment. Asking everyone to write build scripts that check the terminal state to know whether to pass --no-color or not is a non-starter, IMHO.

**Comment by nex3** [comment] 2015-09-08 21:24
As [this comment](https://github.com/dart-lang/test/issues/19#issuecomment-75620970) mentions, the plan is to use `stdioType` to detect whether we're printing to a terminal or a pipe.

**Comment by grouma** [comment] 2018-06-15 17:33
Closing: Working as intended.

**Closed by grouma** 2018-06-15 17:33 UTC
Labels: blocked, bug

**Comment by osa1** [comment] 2025-08-13 10:22
Is this really working as intended? `package:test` still prints color codes and other control characters to files.

Should this be reopened?

**Comment by natebosch** [comment] 2025-08-16 01:29
> Dart standard library has functions for it

We're already using the field on `stdout` for this.

https://github.com/dart-lang/test/blob/9354f239b0eb42a459200b432893d7d026056391/pkgs/test_core/lib/src/util/io.dart#L98-L102

**Comment by osa1** [comment] 2025-10-01 08:34
If anyone wants to fix this, the problem is in this code: https://github.com/dart-lang/test/blob/a16f14975c5625ef99abc71f7e91bca5d8e55054/pkgs/test_core/lib/src/scaffolding.dart#L63-L69

Here `color: true` part would depend on `stdout`, but apparently it can't for the reasons discussed here: https://github.com/dart-lang/test/pull/2540#discussion_r2345459431

I gave up after a few hours, maybe someone else can figure out how to properly initialize `stdout` here.

In the meantime, I'd reopen this issue as it's clearly not fixed.
