### ISSUE TITLE
Url encoding in path issue?

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/test#54] opened 2015-04-01 21:09 UTC
I tried running `pub run unittest:unittest` and got the following error:

```
Failed to load "test\invocation_maker_test.dart":
Unhandled exception:
Uncaught Error: FileSystemException: Cannot open file, path = 'C:\Users\se136c\Documents\GitHub\unscripted\master\test%5Cpackages\test\src\runner\vm\isolate_listener.dart' (OS Error: The system cannot find the path specified.
, errno = 3)
```

Notice the `%5C` in the path.  I assume that's the issue?

**Comment by kevmoo** [comment] 2015-04-01 21:10
Did you update to latest?

The name of the package is now test: pub run test:test

**Comment by nex3** [comment] 2015-04-01 21:28
Duplicate of #44.

**Closed by nex3** 2015-04-01 21:28 UTC
