### ISSUE TITLE
pkg/test VM tests flaky timeout on Travis

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#599] opened 2017-05-01 17:12 UTC
But not locally.

**Comment by grouma** [comment] 2017-05-02 21:44
After some initial debugging it appears that the tests hang do to some unawaited futures. I intend to add a workaround until I can track down the root cause.

**Comment by grouma** [comment] 2017-05-02 21:56
Further flakiness is due to the fact that travis can execute the tests slowly which causes extra prints in the reports. I haven't determined a good fix for this yet.

**Comment by grouma** [comment] 2017-05-06 00:32
This was closed with https://github.com/dart-lang/test/pull/608

**Comment by grouma** [comment] 2017-05-08 16:45
Accidentally closed. This should remain open until the root cause is found.

**Comment by grouma** [comment] 2017-08-04 03:44
It appears the flaky test consistently resides in shard 3: https://travis-ci.org/dart-lang/test/builds/260833022

**Comment by srawlins** [comment] 2018-01-04 22:52
@grouma, you say "extra prints in the reports", can you elaborate?

At dart-lang/markdown#191, we're seeing a similar issue, and @kevmoo found that it can be worked around by using `--reporter expanded` instead of `--reporter compact`.

**Comment by kevmoo** [comment] 2018-01-04 22:57
Tiny delta. For markdown, the tests don't complete and we consistently get a `Unhandled exception:` output...

Not sure...

**Comment by grouma** [comment] 2018-01-04 22:59
The test runner will give command line updates every second or so. If the test took longer to run it would give additional output compared to what was expected. This caused tests to fail. I resolved the issue by updating tests to use more lenient matchers. For example: https://github.com/dart-lang/test/commit/d6cd857a9a7e5b026e999d63c967c94eb9914a92

**Closed** 2021-06-23 21:36 UTC
