### ISSUE TITLE
pub run test directory/ only runs tests from single child directory

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/test#1116] opened 2019-12-05 05:12 UTC
With the command `pub run test test/commands.shard/` (For example https://cirrus-ci.com/task/6656280311103488). The directory structure is:

```
test/
  commands.shard/
    hermetic/
    permeable/
    README.md
```

When executing tests in the `commands.shard` subdirectory of the flutter_tool, only the tests from the permeable subdirectory are executed.

If I change the last path to include wildcards with `test/commands.shard/**/*_test.dart`, I can force every test to be run. Still, this is incredibly surprising behavior.

Dart 2.7.0 (build 2.7.0-dev.2.1 413867d678)
test: 1.9.4

**Comment by jonahwilliams** [comment] 2019-12-05 20:53
FYI @jakemac53

**Comment by jonahwilliams** [comment] 2019-12-05 21:38
More surprising behavior:

```
jonahwilliams-macbookpro2:flutter_tools jonahwilliams$ pub run test test/commands.shard/
00:42 +9: test/commands.shard/permeable/format_test.dart: format a file                                                                  jonahwilliams-macbookpro2:flutter_tools jonahwilliams$ pub run test test/commands.shard
00:56 +31: test/commands.shard/permeable/test_test.dart: flutter test should not have extraneous error messages                          jonahwilliams-macbookpro2:flutter_tools jonahwilliams$ pub run test test/commands.shard
00:47 +27: test/commands.shard/permeable/create_test.dart: (setUpAll) 
```

**Comment by grouma** [comment] 2019-12-05 22:59
I dug into this a bit. I have confirmed that all test files are properly loaded. I think the test runner is dying. I'm not sure why yet but I think there is a problematic test within `commands.shard`.

**Comment by grouma** [comment] 2019-12-05 23:13
It looks like this test is problematic:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart

**Comment by grouma** [comment] 2019-12-05 23:19
Looks like specifically this test:
https://github.com/flutter/flutter/blob/cb0dcbe1a9bcd1f4db44e8a1efbee294ad7d3fb4/packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart#L240

Closing this as this doesn't appear to be a test issue, unless you find that the test runner should not have died in this specific case. Please re-open.

**Closed by grouma** 2019-12-05 23:19 UTC

**Comment by jonahwilliams** [comment] 2019-12-05 23:26
Thanks @grouma !

**Comment by Hixie** [comment] 2019-12-09 18:42
Just for future archaeological purposes, can someone explain how that test was problematic?

**Comment by grouma** [comment] 2019-12-09 18:48
The test was calling `io.exit` which was causing the VM to terminate.

There are more details in https://github.com/flutter/flutter/pull/46181
