### ISSUE TITLE
Dart unit test not working with content-shell on ubuntu and windows machine

### ISSUE THREAD

**Issue by ashokdudhade** [dart-lang/test#276] opened 2015-06-17 14:19 UTC
I have dart unit tests written using test: '>=0.12.1 <0.13.0' library. When I try to run tests using Dartium it works perfectly, but using content-shell it throws error.

```
pub run test test/unit -p content-shell
Failed to start content shell: Bad state: Stream has already been listened to..
```

Note: I have tried it using ubuntu and windows machine and content shell is in path.

[Stackoverflow question](http://stackoverflow.com/questions/30874952/dart-unit-test-not-working-with-content-shell)

**Comment by nex3** [comment] 2015-06-17 20:28
What version of content shell do you have installed? Where did you get it? Is there a stack trace attached to that error? What actual version of `test` are you using?

**Comment by ashokdudhade** [comment] 2015-06-17 20:36
Test version is test: '>=0.12.1 <0.13.0' .
Content shell was downloaded [from](http://gsdview.appspot.com/dart-archive/channels/stable/release/latest/dartium/)
Got these details from [here](https://pub.dartlang.org/packages/test)

**Comment by nex3** [comment] 2015-06-17 20:48
> Test version is test: '>=0.12.1 <0.13.0' .

This isn't a version, it's a version range. It specifies what versions of `test` you allow, not what version you actually have. You can run `pub run test --version` to find the actual version.

> Content shell was downloaded [from](http://gsdview.appspot.com/dart-archive/channels/stable/release/latest/dartium/)

That link always points to the latest release, which can change over time. Do you know which version in particular you got, or at least when you downloaded it?

What about a stack trace?

**Comment by ashokdudhade** [comment] 2015-06-17 21:01
test version is 0.12.3.
Content shell was downloaded on Jun 5 2015. (content_shell-linux-x64-release.zip)
It does not give any stack trace with this error.

**Comment by nex3** [comment] 2015-06-17 21:03
One more question: what version of Dart are you using?

**Comment by ashokdudhade** [comment] 2015-06-17 21:04
Dart VM version: 1.10.1 (Mon May 11 15:56:35 2015) on "linux_x64"

**Comment by nex3** [comment] 2015-06-17 21:10
I can't reproduce this, even with identical `test`, content shell, and Dart versions. Can you provide a full application that's demonstrating this error, including a `pubspec.lock`?

**Comment by ashokdudhade** [comment] 2015-06-17 21:36
Check the example [at](https://github.com/ashokdudhade/DartUnitTestDemo)

**Comment by kevmoo** [comment] 2015-06-17 21:53
Passed for me on `1.11.0-dev.5.2` on Mac.

**Comment by ashokdudhade** [comment] 2015-06-17 21:55
On Mac it works, I'm facing issues on Ubuntu and windows.

**Comment by nex3** [comment] 2015-06-17 22:18
> Check the example [at](https://github.com/ashokdudhade/DartUnitTestDemo)

I can't reproduce with this repo on Ubuntu. It also doesn't have a `pubspec.lock` file, though; please include one so I can be sure I'm using all the same package versions as you.

**Comment by ashokdudhade** [comment] 2015-06-17 22:31
Added pubspec.lock file.

**Comment by nex3** [comment] 2015-06-17 22:32
I'm sorry, but I still can't reproduce the error. I hate to say it, but at this point there's not much I can do here.

**Comment by jdhom** [comment] 2015-06-26 23:20
Just an FYI... this fails on all 3 windows machines at my shop too.

**Comment by kevmoo** [comment] 2015-06-26 23:23
@jdhom what version of the Dart VM do you have installed?
What version of the test package are you using?

**Comment by jdhom** [comment] 2015-06-26 23:26
@kevmoo will get you the details Monday... 1.10.x vintage. folks are just now moving to 1.11 stable, can check that as well.  thanks for follow-up.

**Comment by kevmoo** [comment] 2015-06-30 17:26
@jdhom Any updates here?

**Comment by ashokdudhade** [comment] 2015-06-30 21:39
This isn't working for me on my windows machine as well.

**Comment by kevmoo** [comment] 2015-07-02 22:33
I have a windows VM set up. I'll dig in...

**Comment by kevmoo** [comment] 2015-07-06 23:14
@jdhom @ashokdudhade I've got this working on a windows VM w/ Dart 1.12 SDK.

For either of you: can you run `content_shell.exe` from your shell? Do you have it installed?

I downloaded the latest version, put 'drt-win-full-dev-1.12.0-dev.1.1.0` on my path – works like a charm.

**Comment by kevmoo** [comment] 2015-07-07 21:05
@jdhom @ashokdudhade Ping?

I want to make sure we help you here. I'm going to consider this closed in the mean time.

**Closed by kevmoo** 2015-07-07 21:05 UTC
Labels: bug, needs info

**Comment by ashokdudhade** [comment] 2015-07-08 21:45
@kevmoo  I downloaded the "drt-win-full-stable-1.11.1.0" version of content shell and it still does not work.

**Comment by kevmoo** [comment] 2015-07-08 22:26
@ashokdudhade can you run 'content_shell.exe' from your command line? Is it in your path?

**Comment by ashokdudhade** [comment] 2015-07-08 23:00
Yes its there us my path.


Thanks,

Ashok Dudhade





On Wed, Jul 8, 2015 at 3:26 PM -0700, "Kevin Moore" <notifications@github.com> wrote:
@ashokdudhade can you run 'content_shell.exe' from your command line? Is it in your path?

---

**Comment by ashokdudhade** [comment] 2015-07-09 16:30
Good news! After upgrading my dart version to Dart VM version: 1.11.0 tests are working fine.
Thanks @kevmoo

**Comment by kevmoo** [comment] 2015-07-09 16:58
Woo hoo! :metal:
