### ISSUE TITLE
`expect.dart` removal causes lots of issue

### ISSUE THREAD

**Issue by argahutama** [dart-lang/test#2025] opened 2023-05-29 03:07 UTC
I'm not able to run the codes with the latest stable Flutter version because of these errors:

```
: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/test_api-0.6.0/lib/expect.dart': No such file or directory
_goldens_io.dart:12
import 'package:test_api/expect.dart' show fail;

: Error: Type 'AsyncMatcher' not found.
_matchers_io.dart:44
class MatchesGoldenFile extends AsyncMatcher {

: Error: Type 'Description' not found.
_matchers_io.dart:120
  Description describe(Description description) {
  
  : Error: Type 'Description' not found.
_matchers_io.dart:120
  Description describe(Description description) {
  
  : Error: Type 'Matcher' not found.
matchers.dart:39
const Matcher findsNothing = _FindsWidgetMatcher(null, 0);
      ^^^^^^^
: Error: Type 'Matcher' not found.
matchers.dart:55
const Matcher findsWidgets = _FindsWidgetMatcher(1, null);
      ^^^^^^^
: Error: Type 'Matcher' not found.
matchers.dart:71
const Matcher findsOneWidget = _FindsWidgetMatcher(1, 1);
```

**Comment by argahutama** [comment] 2023-05-29 06:20
Workaround:
It can be solved by adding https://pub.dev/packages/test_api/versions/0.5.2 in the pubspec.yaml (workaround)

**Comment by jakemac53** [comment] 2023-05-30 14:42
It sounds like you are likely running `flutter test` but without a dependency on the `flutter_test` package, see https://github.com/flutter/flutter/issues/91107 for some more details about why that dependency is necessary.

Adding a dependency override on test_api (or setting a specific version as a normal dep) will run into other issues soon, so you will want to find a better solution.

**Comment by jakemac53** [comment] 2023-05-30 14:49
> Not really
> [firebase/flutterfire#11040](https://github.com/firebase/flutterfire/issues/11040)
> [flutter/flutter#127571](https://github.com/flutter/flutter/issues/127571)

I am not sure what you mean here - afaik likely all of these issues are a result of a missing dependency on `flutter_test`.

**Comment by jakemac53** [comment] 2023-05-30 14:51
Also note that anybody following the advice to pin the test_api version will mostly likely be broken again the next time they upgrade flutter.

**Comment by argahutama** [comment] 2023-05-30 14:52
Everything worked fine until I upgraded the Flutter version to the latest one @jakemac53 

Any solution for it?

**Comment by jakemac53** [comment] 2023-05-30 14:54
@argahutama did you add a dependency on `flutter_test`?

**Comment by argahutama** [comment] 2023-05-30 15:07
> @argahutama did you add a dependency on `flutter_test`?

Yes, on `dev_dependencies`.

**Comment by jakemac53** [comment] 2023-05-30 15:08
Are you pinning `package:test_api`? Can I see your full pubspec?

**Comment by jakemac53** [comment] 2023-05-30 15:08
Also what version of flutter are you on now?

**Comment by natebosch** [comment] 2023-06-06 20:00
Closing since we haven't seen a reproduction case that doesn't point back to https://github.com/flutter/flutter/issues/91107

**Closed by natebosch** 2023-06-06 20:00 UTC
