### ISSUE TITLE
Tests are not running when returning a Future from tearDown's body function

### ISSUE THREAD

**Issue by Amir-P** [dart-lang/test#1656] opened 2022-01-04 10:13 UTC
**Copied from https://github.com/flutter/flutter/issues/96048 since it's happening with this package too:**

I found this issue after converting `tearDown`'s body function from block function to arrow function in which I was calling `streamController.close()` which returns a `Future`. Here is a simple reproducible code to run using `flutter test test/test.dart`:

```dart
import 'dart:async';

import 'package:test/test.dart';

void main() {
  late StreamController streamController;
  
  setUp(() {
    streamController = StreamController();
  });

  tearDown(() => streamController.close());

  test('expect', () {
    expect(true, true);
  });
}
```

This test will not run and will fail with `TimeoutException`.

```
dart test test/test.dart 
00:32 +0 -1: expect [E]                                                        
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
  dart:isolate  _RawReceivePortImpl._handleMessage
  
00:32 +0 -1: Some tests failed.  
```

Now if you convert `tearDown(() => streamController.close());` to `tearDown(() { streamController.close(); });` the test will run and pass with no problem.

This problem is not specific to `flutter_test` and it happens with dart's `test` package too.

`flutter doctor -v`:
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-arm, locale
    en-US)
    • Flutter version 2.8.1 at /Users/amirpanahandeh/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/amirpanahandeh/SDK
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/amirpanahandeh/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7727

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

**Comment by jakemac53** [comment] 2022-01-04 15:33
It sounds like the `Future` returned by `streamController.close()` must not be completing? If `tearDown` returns a future then it waits for the future to complete before considering the test complete.

**Comment by jakemac53** [comment] 2022-01-04 15:36
Ya, consider this program:

```dart
import 'dart:async';

void main() {
  var streamController = StreamController();
  print('closing');
  streamController.close().then((_) {
    print('closed');
  });
}
```

This only logs `closing` and not `closed`.

Unfortunately this looks to be working as intended, from https://api.dart.dev/stable/2.15.1/dart-async/StreamController/close.html

> If no one listens to a non-broadcast stream, or the listener pauses and never resumes, the done event will not be sent and this future will never complete.

**Comment by jakemac53** [comment] 2022-01-04 15:37
I am closing this as `as designed`, it appears to be an unfortunate side effect of the design of that `close` method. I don't see anything this package could do about it.

**Closed** 2022-01-04 15:36 UTC
Labels: as designed
